# Generated by Django 5.1.4 on 2024-12-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
